on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      KP_USER: ${{ secrets.KP_USER }}
      KP_PW: ${{ secrets.KP_PW }}
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/jammy/latest"

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: |
            any::pkgdown
            any::animation
            any::cfbfastR
            any::fastRhockey
            any::ggimage
            any::knitr
            any::oddsapiR
            any::pacman
            any::pak
            any::ragg
            any::remotes
            any::rsconnect
            any::sportyR
            any::tictoc
            any::wehoop
            any::zoo
            local::.
          needs: website
      - name: Install system dependencies
        run: |
          pak::pkg_install("hadley/emo")
          pak::pkg_install("r-lib/pkgapi")
        shell: Rscript {0}

      - name: Deploy package
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
